PyTorch
====


**PyTorch** is an open source machine learning framework with two main features:
  *  tensor computation (GPU-accelerated), *a.k.a.* a replacement for NumPy,
  *  deep neural networks built on a tape-based autograd system.


In [1]:
# import the library
import torch
import numpy as np


Tensors
-----


`torch.Tensor` is the central class of the package. Tensors are similar to NumPy's `np.ndarray`s.

###  1. Create tensors


In [2]:
# construct an empty 5x3 matrix, uninitialized
x = torch.empty(5, 3)
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
# construct a randomly initialized 5x3 matrix
x = torch.rand(5, 3)  # uniform
print(x)

x = print(torch.randn(5, 3))  # normal ~ N(0, 1)
print(x)


tensor([[0.5191, 0.2018, 0.3893],
        [0.9440, 0.1548, 0.1060],
        [0.1154, 0.7860, 0.9539],
        [0.9543, 0.0807, 0.1180],
        [0.1367, 0.3283, 0.1017]])
tensor([[ 0.2430,  0.9436,  0.0059],
        [ 1.4308, -2.3691,  0.0606],
        [-1.8024,  1.5526,  0.1833],
        [-0.2010,  2.5713,  0.2707],
        [-0.2531,  0.3503, -0.2024]])
None


In [4]:
# construct a matrix filled with zeros, specify dtype as `long`
x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# construct a tensor from data
x = torch.tensor([5.5, 3])  # from list
print(x)


tensor([5.5000, 3.0000])


In [6]:
# create tensors based on existing tensors, reusing their parameters
x = torch.ones(8, 4, dtype=torch.long)
print(x)
print('-----')

# new_* methods reuse source tensor params, unless overridden
print(x.new_ones(5, 3))
print(x)  # not modified - new_* always copy data
print('-----')

# zeros_like, ones_like, empty_like, full_like, rand_like, randint_like, randn_like
# create tensor of the same size, but different values
print(torch.randn_like(x, dtype=torch.double))
print(x)  # not modified


tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
-----
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
-----
tensor([[ 1.3712,  2.2850,  0.5070,  1.2813],
        [ 1.2718,  0.8674,  0.6304,  1.1826],
        [ 0.1918, -1.3667,  0.3102, -0.1653],
        [-1.8360,  1.2801, -1.5472, -1.8649],
        [ 0.8578,  0.8026,  2.3865,  0.4935],
        [-1.5432, -0.3317,  1.3774,  0.4467],
        [-0.2650,  1.0626, -0.1891, -0.3425],
        [-0.7851,  0.2195,  0.4022, -0.5178]], dtype=torch.float64)
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1

###  2. Tensor attributes and operations


**tensor types**

[torch.tensor](https://pytorch.org/docs/stable/tensors.html#torch-tensor)


In [7]:
# indexing and slicing
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x)
print('-----')

print(x[0, 3])
print(x[1][2])
print('-----')

print(x[:, :1])
print(x[::2])
print(x[::2][0])
print(x[::2][0][1]) # multiple indexing is applied to the returned tensor


tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
-----
tensor(4)
tensor(7)
-----
tensor([[1],
        [5],
        [9]])
tensor([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]])
tensor([1, 2, 3, 4])
tensor(2)


In [8]:
# get value from a single-value tensor
x = torch.tensor([[[1]]], dtype=torch.uint8)
print(x)
print(x.item())
print('-----')

x = torch.tensor(2.5, dtype=torch.float64)
print(x)
print(x.item())


tensor([[[1]]], dtype=torch.uint8)
1
-----
tensor(2.5000, dtype=torch.float64)
2.5


In [9]:
# get tensor size
x = torch.rand(5, 3)
print(x.size())  # <- is a tuple
size_tuple = x.size()


torch.Size([5, 3])


In [10]:
# multiple syntaxes for adding
x = torch.ones(2, 3, dtype=torch.long)
y = torch.randint(high=3, size=(2, 3))
print(x + y)  # use `+` operator

print(torch.add(x, y))  # use torch function

result = torch.empty(2, 3)
torch.add(x, y, out=result)  # provide an output tensor <- will return value as well
print(result)

y.add_(x)  # in-place addition
print(y)

# any method followed by `_` modifies the tensor in-place
# e.g. `copy_`, `t_`


tensor([[3, 2, 3],
        [2, 2, 3]])
tensor([[3, 2, 3],
        [2, 2, 3]])
tensor([[3., 2., 3.],
        [2., 2., 3.]])
tensor([[3, 2, 3],
        [2, 2, 3]])


In [11]:
# resizing tensors
x = torch.rand(4, 4)
print(x.view(16))
print(x.view(1, 8, 2))
print('-----')

reshaped = x.view(2, -1, 4)  # `-1` indicates size inferred from other dimensions
print(reshaped.size())
print(reshaped)


tensor([0.9643, 0.4988, 0.8848, 0.1339, 0.1901, 0.8206, 0.8670, 0.1985, 0.8874,
        0.4964, 0.5432, 0.0844, 0.2389, 0.2434, 0.4460, 0.8255])
tensor([[[0.9643, 0.4988],
         [0.8848, 0.1339],
         [0.1901, 0.8206],
         [0.8670, 0.1985],
         [0.8874, 0.4964],
         [0.5432, 0.0844],
         [0.2389, 0.2434],
         [0.4460, 0.8255]]])
-----
torch.Size([2, 2, 4])
tensor([[[0.9643, 0.4988, 0.8848, 0.1339],
         [0.1901, 0.8206, 0.8670, 0.1985]],

        [[0.8874, 0.4964, 0.5432, 0.0844],
         [0.2389, 0.2434, 0.4460, 0.8255]]])


All tensor operations are described in the [docs](https://pytorch.org/docs/torch).


###  3. PyTorch & NumPy


When creating numpy array from torch tensor they will share their memory locations (if the tensor is on CPU).


In [12]:
a = torch.ones(5)
print(a)

b = a.numpy() #  convert tensor to `np.ndarray`
print(b)

a.add_(1)
print(a)
print(b)


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Same happens when converting from numpy array to torch tensor.


In [13]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Unless you use `torch.tensor`, which copies the data.


In [14]:
a = np.ones(5)
b = torch.tensor(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


###  4. CUDA


Tensors can be moved between devices using `.to` method. This part will work only if you use a machine with CUDA GPU.


In [15]:
if torch.cuda.is_available():
    gpu = torch.device("cuda")
    x = torch.ones(5, 5, device=gpu)
    y = torch.randint(3, (5, 5))
    y.to(gpu)
    result = x + y
    print(result)
    print(result.to("cpu", dtype=torch.double))
else:
    print('No CUDA device available.')


No CUDA device available.


------

Exercises
-----


1. Create two tensors of shape $\left(27, 19, 31\right)$ and $\left(31, 111\right)$. Use any of the random tensor creation methods. Make sure their dtype is floating-point.


2. Perform matrix multiplication of the tensors (`@`, `torch.matmul` or `tensor.matmul_`). What is the size of the new tensor?

3. Perform summing across the last dimension (pass optional argument `dim=-1` to `torch.sum`). What is the size of the new tensor?

4. Use `torch.mean` to calculate average across the first dimension of the `summed` tensor.